name: "wiz-cli"
on: [push]

jobs:
  wiz-cli-iac-scan:
    name: "Wiz-cli IaC Scan"
    runs-on: ubuntu-latest
    env:
      SCAN_PATH: "./" # Set the relative path in the repo to scan
      POLICY: "MaxSCCPolicy" # Set the desired Wiz CLI policy to use

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      # Checkout the repository to the GitHub Actions runner
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Download Wiz CLI
        run: curl -o wizcli https://downloads.wiz.io/v1/.wizcli/latest/wizcli-linux-amd64 && chmod +x wizcli

      - name: Run Wiz CLI IaC scan
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}
        run: ./wizcli scan dir "$SCAN_PATH" --policies "$POLICY"